# Generated by Django 2.2 on 2020-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vita',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
