# Generated by Django 2.2 on 2020-09-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200912_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_users', 'Может просмотреть состав группы')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
