# Generated by Django 2.2 on 2020-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.TextField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=3000, verbose_name='Статус')),
                ('completion_date', models.DateField(auto_now_add=True, null=True, verbose_name='Время завершения')),
            ],
        ),
    ]
