# Generated by Django 2.2 on 2020-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task_type',
            name='type',
            field=models.CharField(max_length=15, verbose_name='Тип'),
        ),
    ]
