# Generated by Django 2.2 on 2020-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200805_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ManyToManyField(related_name='types', to='webapp.Task_type', verbose_name='Тип'),
        ),
    ]
