# Generated by Django 2.2 on 2020-08-13 08:42

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200810_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.validators.descriptions_validator], verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[webapp.validators.name_char, webapp.validators.MinLengthValidator(5)], verbose_name='Описание'),
        ),
    ]
