# Generated by Django 2.2 on 2020-09-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200910_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_change_group', 'Может изменить состав группы'), ('can_view_users', 'Может смотреть список пользователей')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
