# Generated by Django 2.2 on 2020-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200912_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_change_group', 'Может изменить состав группы')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
